name: Build
on:
    push:
        branches:
            - "main"
    pull_request:

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php_versions: ['8.1', '8.2']
                symfony_version: ['6.1', '6.2', '6.3']
                mode: [low, high]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_versions }}
                  coverage: none

            - name: Get Composer Cache Directory
              id: composer-cache-dir
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php_versions }}-${{ matrix.symfony_version }}-${{ matrix.mode }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php_versions }}-${{ matrix.symfony_version }}-${{ matrix.mode }}-composer-

            - name: Install dependencies
              run: |
                  composer config extra.symfony.require "${{ matrix.symfony_version }}"
                  [[ "${{ matrix.mode }}" = "low" ]] && composer update --no-progress --prefer-lowest || true
                  [[ "${{ matrix.mode }}" = "high" ]] && composer update --no-progress || true
                  vendor/bin/simple-phpunit install

            - name: Run tests
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'weak'
              run: vendor/bin/simple-phpunit

    tests-legacy:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php_versions: ['8.0', '8.1', '8.2']
                symfony_version: ['5.4', '6.0']
                mode: [low, high]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_versions }}
                  coverage: none

            - name: Get Composer Cache Directory
              id: composer-cache-dir
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php_versions }}-${{ matrix.symfony_version }}-${{ matrix.mode }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php_versions }}-${{ matrix.symfony_version }}-${{ matrix.mode }}-composer-

            - name: Install dependencies
              run: |
                  composer config extra.symfony.require "${{ matrix.symfony_version }}"
                  [[ "${{ matrix.mode }}" = "low" ]] && composer update --no-progress --prefer-lowest || true
                  [[ "${{ matrix.mode }}" = "high" ]] && composer update --no-progress || true
                  vendor/bin/simple-phpunit install

            - name: Run tests
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'weak'
              run: vendor/bin/simple-phpunit
